# gender
male = {'he', 'man', 'john', 'himself', 'son', 'father', 'boy', 'male'}
female = {'she', 'woman', 'mary', 'herself', 'daughter', 'mother', 'girl', 'female'}
aligned_male_female = {('she', 'he'), ('woman', 'man'), ('mary', 'john'), ('herself', 'himself'), ('daughter', 'son'), ('mother', 'father'), ('girl', 'boy'), ('female', 'male')} 
gender = male | female

male_names = {'andrew', 'brad', 'frank', 'geoffrey', 'jack', 'jonathan', 'josh', 'matthew', 'neil', 'peter', 'roger', 'stephen', 'alonzo', 'alphonse', 'hakim', 'jamal', 'jamel', 'jerome', 'leroy', 'lionel', 'marcellus', 'terrence', 'tyrone', 'wardell', 'alberto', 'alejandro', 'alfredo', 'antonio', 'cesar', 'jose', 'juan', 'miguel', 'pedro', 'rigoberto', 'rogelio'}
female_names = {'aisha', 'keisha', 'lakisha', 'latisha', 'latoya', 'malika', 'nichelle', 'shereen', 'tamika', 'tanisha', 'yolanda', 'yvette', 'adriana', 'alejandra', 'alma', 'brenda', 'carolina', 'iliana', 'karina', 'liset', 'maria', 'mayra', 'sonia', 'yesenia', 'carrie', 'colleen', 'ellen', 'emily', 'heather', 'katie', 'megan', 'melanie', 'nancy', 'rachel', 'sarah', 'stephanie'}
gender_names = male_names | female_names

male_all = male | male_names 
female_all = female | female_names
gender_all = gender | gender_names

# race

white = {"harris", "nelson", "robinson", "thompson", "moore", "wright", "anderson", "clark", "jackson", "taylor", "scott", "davis", "allen", "adams", "lewis", "williams", "jones", "wilson", "martin", "johnson"}
hispanic = {"castillo", "gomez", "soto", "gonzalez", "sanchez", "rivera", "martinez", "torres", "rodriguez", "perez", "lopez", "medina", "diaz", "garcia", "castro", "cruz"}
asian = {"cho", "wong", "tang", "huang", "chu", "chung", "ng", "wu", "liu", "chen", "lin", "yang", "kim", "chang", "shah", "wang", "li", "khan", "singh", "hong"}
race = white | hispanic | asian 

# targets
gender_special_targets = ["plumber", "secretary", "chiropractor", "businessman", "businesswoman"]
race_special_targets = ["pilot", "janitor", "scientist", "librarian", "designer"]
gender_census_targets = {'manager', 'mailperson', 'farmer', 'painter', 'bailiff', 'tradesperson', 'doorkeeper', 'gardener', 'photographer', 'cook', 'mechanic', 'proprietor', 'janitor', 'secretary', 'plumber', 'plasterer', 'peddler', 'clerical', 'veterinarian', 'pilot', 'electrician', 'chemist', 'sailor', 'engineer', 'dancer', 'welder', 'scientist', 'dentist', 'postmaster', 'soldier', 'lumberjack', 'doctor', 'boilermaker', 'attendant', 'setter', 'technician', 'designer', 'typesetter', 'waitstaff', 'therapist', 'bartender', 'nurse', 'lawyer', 'musician', 'architect', 'toolmaker', 'smith', 'shoemaker', 'police', 'jeweler', 'carpenter', 'huckster', 'administrator', 'fireperson', 'baker', 'clergy', 'millwright', 'broker', 'auctioneer', 'sales', 'optometrist', 'salesperson', 'instructor', 'sheriff', 'upholsterer', 'teacher', 'machinist', 'guard', 'tailor', 'official', 'porter', 'judge', 'operator', 'laborer', 'physician', 'inspector', 'compositor', 'athlete', 'professor', 'librarian', 'driver', 'pharmacist', 'cabinetmaker', 'surveyor', 'clerk', 'conductor', 'draftsperson', 'artist', 'surgeon', 'molder', 'author', 'housekeeper', 'newsperson', 'entertainer', 'mason'}
race_census_targets = {'manager', 'mailperson', 'farmer', 'painter', 'bailiff', 'tradesperson', 'doorkeeper', 'gardener', 'photographer', 'cook', 'mechanic', 'proprietor', 'janitor', 'secretary', 'plumber', 'plasterer', 'peddler', 'clerical', 'veterinarian', 'electrician', 'pilot', 'chemist', 'sailor', 'engineer', 'dancer', 'welder', 'scientist', 'dentist', 'postmaster', 'soldier', 'lumberjack', 'doctor', 'boilermaker', 'attendant', 'setter', 'technician', 'designer', 'typesetter', 'waitstaff', 'therapist', 'bartender', 'nurse', 'lawyer', 'musician', 'architect', 'toolmaker', 'smith', 'shoemaker', 'police', 'jeweler', 'carpenter', 'huckster', 'administrator', 'fireperson', 'baker', 'clergy', 'millwright', 'broker', 'auctioneer', 'sales', 'optometrist', 'salesperson', 'instructor', 'sheriff', 'upholsterer', 'teacher', 'machinist', 'guard', 'tailor', 'official', 'porter', 'judge', 'operator', 'laborer', 'physician', 'inspector', 'compositor', 'athlete', 'professor', 'librarian', 'driver', 'pharmacist', 'cabinetmaker', 'surveyor', 'clerk', 'conductor', 'draftsperson', 'artist', 'surgeon', 'molder', 'author', 'housekeeper', 'newsperson', 'entertainer', 'mason'}
gender_2010_targets = {'weaver', 'paperhanger', 'millwright', 'boilermaker', 'mechanic', 'conductor', 'bartender', 'carpenter', 'bankteller', 'salesperson', 'cabinetmaker', 'compositor', 'nutritionist', 'mason', 'entertainer', 'mailperson', 'artist', 'designer', 'shoemaker', 'laborer', 'geologist', 'dentist', 'attendant', 'lumberjack', 'scientist', 'baker', 'secretary', 'professor', 'sales', 'surveyor', 'tradesperson', 'physicist', 'sailor', 'bookbinder', 'newsperson', 'toolmaker', 'economist', 'musician', 'technician', 'guard', 'veterinarian', 'porter', 'architect', 'engineer', 'upholsterer', 'pilot', 'surgeon', 'athlete', 'instructor', 'author', 'housekeeper', 'physician', 'sheriff', 'police', 'official', 'broker', 'typesetter', 'jeweler', 'setter', 'accountant', 'gardener', 'farmer', 'psychologist', 'chiropractor', 'clergy', 'chemist', 'lawyer', 'manager', 'fireperson', 'smith', 'judge', 'bailiff', 'photographer', 'teacher', 'doctor', 'administrator', 'clerical', 'statistician', 'plasterer', 'conservationist', 'machinist', 'proprietor', 'dancer', 'waitstaff', 'dietitian', 'painter', 'operator', 'pharmacist', 'electrician', 'janitor', 'welder', 'draftsperson', 'therapist', 'plumber', 'soldier', 'driver', 'inspector', 'doorkeeper', 'librarian', 'nurse', 'clerk', 'cashier', 'cook', 'optometrist'}
race_2010_targets = {'weaver', 'millwright', 'boilermaker', 'mechanic', 'conductor', 'soldier', 'bartender', 'paperhanger', 'newsperson', 'carpenter', 'bankteller', 'clerical', 'salesperson', 'cabinetmaker', 'compositor', 'mason', 'entertainer', 'mailperson', 'artist', 'designer', 'statistician', 'shoemaker', 'geologist', 'dentist', 'attendant', 'accountant', 'scientist', 'baker', 'secretary', 'professor', 'sales', 'tradesperson', 'physicist', 'sailor', 'bookbinder', 'laborer', 'toolmaker', 'economist', 'musician', 'guard', 'veterinarian', 'porter', 'architect', 'engineer', 'surgeon', 'clergy', 'athlete', 'instructor', 'housekeeper', 'physician', 'sheriff', 'police', 'author', 'official', 'upholsterer', 'broker', 'technician', 'typesetter', 'jeweler', 'setter', 'chiropractor', 'gardener', 'farmer', 'psychologist', 'chemist', 'lumberjack', 'lawyer', 'manager', 'smith', 'judge', 'cook', 'bailiff', 'photographer', 'teacher', 'doctor', 'administrator', 'plasterer', 'conservationist', 'machinist', 'proprietor', 'dancer', 'waitstaff', 'dietitian', 'painter', 'operator', 'pharmacist', 'plumber', 'electrician', 'optometrist', 'janitor', 'welder', 'fireperson', 'surveyor', 'driver', 'draftsperson', 'therapist', 'inspector', 'pilot', 'doorkeeper', 'librarian', 'nurse', 'clerk', 'cashier', 'nutritionist'} 
face_validity_targets = {'carpenter', 'pilot', 'soldier', 'nurse', 'dancer', 'librarian', 'businessman', 'businesswoman'}
ordered_face_validity_targets = ['carpenter', 'dancer', 'librarian', 'nurse', 'pilot', 'soldier', 'businessman', 'businesswoman']